openapi: 3.0.0
info:
  title: Plannig Poker API
  version: 1.0.0
  description: API to handle Planning Poker requests
servers:
  - url: 'http://localhost:3080'
tags:
  - name: Health
    description: Operations related to health check
  - name: User
    description: Operations related to user management
paths:
  /health:
    get:
      tags:
        - Health
      summary: Check if the server is running
      responses:
        '200':
          description: Server is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  healthy:
                    type: boolean
                    example: true
  /register:
    post:
      tags:
        - User
      summary: Create an account on the system
      requestBody:
        description: Account to be created
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                  description: Name of the user
                email:
                  type: string
                  example: john_doe@example.org
                  description: Email of the user
                password:
                  type: string
                  example: Password@123
                  description: Password of the user
              required:
                - name
                - email
                - password
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: d9954524-334a-4a60-964a-09a299e54d15
                    description: ID of the user
                  name:
                    type: string
                    example: John Doe
                    description: Name of the user
                  email:
                    type: string
                    example: john_doe@example.org
                    description: Email of the user
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: ec55230d-e4d3-4b97-baa6-4702131978e5
                    description: ID of the error
                  message:
                    type: string
                    example: 'Bad request: email should not be empty, email must be a string'
                    description: Message of the error
  /login:
    post:
      tags:
        - User
      summary: Login to the system
      requestBody:
        description: Account to login to
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: john_doe@example.org
                  description: Email of the user
                password:
                  type: string
                  example: Password@123
                  description: Password of the user
              required:
                - email
                - password
      responses:
        '200':
          description: Login made successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ5OTU0NTI0LTMzNGEtNGE2MC05NjRhLTA5YTI5OWU1NGQxNSIsIm5hbWUiOiJEYXZpIEFuZHJhZGUgUG9udGVzIiwiZW1haWwiOiJkYXZpaS5zYXBpZW5zQGdtYWlsLmNvbSIsImlhdCI6MTczOTMyODczNywiZXhwIjoxNzM5MzMyMzM3fQ.XC6p1DAQRazaItFyF_-bBGdF0mNGZzdpoN2eIewWreI
                    description: JWT token to be used on subsequent requests
                  user:
                    $ref: '#/components/schemas/User'
                required:
                  - token
                  - user
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      type: object
      description: User object
      properties:
        id:
          type: string
          example: d9954524-334a-4a60-964a-09a299e54d15
          description: ID of the user
        name:
          type: string
          example: John Doe
          description: Name of the user
        email:
          type: string
          example: john_doe@example.org
          description: Email of the user
      required:
        - id
        - name
        - email
    Error:
      type: object
      properties:
        id:
          type: string
          example: ec55230d-e4d3-4b97-baa6-4702131978e5
          description: ID of the error
        message:
          type: string
          example: '{{error_type}}: {{error_message}}'
          description: Message of the error
