-- Migration file created on 20250223231205
ALTER TABLE organization ADD deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE card ADD deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE project ADD deleted BOOLEAN NOT NULL DEFAULT FALSE;
