post:
  tags:
    - "User"
  summary: "Login to the system"
  requestBody:
    description: "Account to login to"
    required: true
    content:
      application/json:
        schema:
          type: "object"
          properties:
            email:
              type: "string"
              example: "john_doe@example.org"
              description: "Email of the user"
            password:
              type: "string"
              example: "Password@123"
              description: "Password of the user"
          required:
            - "email"
            - "password"
  responses:
    "200":
      description: "Login made successfully"
      content:
        application/json:
          schema:
            type: "object"
            properties:
              token:
                type: "string"
                example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ5OTU0NTI0LTMzNGEtNGE2MC05NjRhLTA5YTI5OWU1NGQxNSIsIm5hbWUiOiJEYXZpIEFuZHJhZGUgUG9udGVzIiwiZW1haWwiOiJkYXZpaS5zYXBpZW5zQGdtYWlsLmNvbSIsImlhdCI6MTczOTMyODczNywiZXhwIjoxNzM5MzMyMzM3fQ.XC6p1DAQRazaItFyF_-bBGdF0mNGZzdpoN2eIewWreI"
                description: "JWT token to be used on subsequent requests"
              user:
                $ref: "../schemas/user.swagger.yaml"
            required:
              - "token"
              - "user"
    "400":
      description: "Bad request"
      content:
        application/json:
          schema:
            $ref: "../schemas/error.swagger.yaml"
    "401":
      description: "Unauthorized"
      content:
        application/json:
          schema:
            $ref: "../schemas/error.swagger.yaml"
